---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "Europe/London"
      time: "09:00"
      day: "monday"
    commit-message:
      prefix: "ci:"

  - package-ecosystem: gomod
    directory: "tools/"
    schedule:
      interval: daily
      time: "09:00"
    commit-message:
      prefix: "go:"
